packages:
  - playground
  - packages/*
catalog:
  '@codemirror/state': ^6
  '@codemirror/view': ^6
  '@types/fs-extra': ^11.0.4
  destr: ^2.0.3
  fs-extra: ^11.3.0
  jiti: ^2.4.2
  shiki: 3.2.1
  tm-grammars: ^1.23.6
  tm-themes: ^1.10.2
  unplugin-external: 0.1.0-beta.3
  usexx: ^0.1.0
  vite: ^6.1.1
  vite-plugin-dts: ^4.5.3
onlyBuiltDependencies:
  - esbuild
